/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#3a090d",
        "on-error-container": "#93000a",
        "on-surface": "#1e1b17",
        "tertiary-fixed": "#ffdad9",
        "secondary-fixed": "#fadcd2",
        "surface-bright": "#fff8f2",
        "primary-fixed": "#ffdad2",
        "inverse-surface": "#33302c",
        "on-primary-fixed": "#2b1611",
        "primary": "#361f1a",
        "on-secondary-fixed-variant": "#56423b",
        "tertiary-fixed-dim": "#ffb3b2",
        "secondary-container": "#fadcd2",
        "secondary-fixed-dim": "#ddc1b7",
        "primary-container": "#4e342e",
        "on-primary-container": "#c19c94",
        "tertiary": "#471215",
        "on-error": "#ffffff",
        "background": "#fff8f2",
        "surface-container-high": "#eee7e0",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#e18e8e",
        "on-background": "#1e1b17",
        "surface-dim": "#dfd9d2",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-variant": "#e8e1db",
        "surface-container-highest": "#e8e1db",
        "on-secondary-fixed": "#271812",
        "surface-tint": "#755750",
        "inverse-on-surface": "#f6f0e9",
        "on-tertiary": "#ffffff",
        "secondary": "#6f5a52",
        "surface-container-low": "#f9f2ec",
        "outline-variant": "#d4c3bf",
        "outline": "#827471",
        "on-tertiary-fixed-variant": "#723335",
        "surface": "#fff8f2",
        "on-secondary-container": "#766057",
        "error": "#ba1a1a",
        "surface-container": "#f4ede6",
        "on-primary-fixed-variant": "#5c403a",
        "on-surface-variant": "#504442",
        "on-primary": "#ffffff",
        "tertiary-container": "#632729",
        "inverse-primary": "#e5beb5",
        "primary-fixed-dim": "#e5beb5"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
